name: Publish gateway

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
        with:
          ref: master
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v7
        with:
          node-version: latest

      - name: Update changelog
        run: npx --yes auto-changelog@latest --output CHANGELOG.md --tag-pattern "v.*"

      - name: Commit and push changelog
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update CHANGELOG.md for ${{ github.ref_name }}"
          file_pattern: CHANGELOG.md
          branch: master

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Create GitHub release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true

      - name: publish module
        run: GOPROXY=proxy.golang.org go list -m github.com/henryhale/gateway@${{ github.ref_name }}
